In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#读取数据
train_set = pd.read_csv("train.csv")
#predict_set = pd.read_csv("test.csv")

In [45]:
predict_set = pd.read_csv("test1.csv")

In [46]:
predict_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
customerID          1000 non-null object
gender              1000 non-null int64
SeniorCitizen       1000 non-null int64
Partner             1000 non-null int64
Dependents          1000 non-null int64
tenure              1000 non-null int64
PhoneService        1000 non-null int64
MultipleLines       1000 non-null int64
InternetService     1000 non-null object
OnlineSecurity      1000 non-null int64
OnlineBackup        1000 non-null int64
DeviceProtection    1000 non-null int64
TechSupport         1000 non-null int64
StreamingTV         1000 non-null int64
StreamingMovies     1000 non-null int64
Contract            1000 non-null int64
PaperlessBilling    1000 non-null int64
PaymentMethod       1000 non-null object
MonthlyCharges      1000 non-null float64
TotalCharges        1000 non-null object
dtypes: float64(1), int64(15), object(4)
memory usage: 156.4+ KB


In [24]:
a=train_set.MonthlyCharges

In [23]:
train_set.MonthlyCharges.

AttributeError: 'Series' object has no attribute 'float'

In [8]:
#最重要的预处理!
#对于非数值型的变量进行清洗
cat_vars=['InternetService','PaymentMethod']
for var in cat_vars:
    cat_list = pd.get_dummies(train_set[var],prefix = var)
    train_with_dummy = train_set.join(cat_list)
    train_set = train_with_dummy

In [9]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6043 entries, 0 to 6042
Data columns (total 28 columns):
customerID                                 6043 non-null object
gender                                     6043 non-null int64
SeniorCitizen                              6043 non-null int64
Partner                                    6043 non-null int64
Dependents                                 6043 non-null int64
tenure                                     6043 non-null int64
PhoneService                               6043 non-null int64
MultipleLines                              6043 non-null int64
InternetService                            6043 non-null object
OnlineSecurity                             6043 non-null int64
OnlineBackup                               6043 non-null int64
DeviceProtection                           6043 non-null int64
TechSupport                                6043 non-null int64
StreamingTV                                6043 non-null int64
Streaming

In [10]:
train_set.drop(train_set[cat_vars].columns, axis = 1, inplace=True)

In [11]:
#df.to_csv('employee_pre.csv')
train_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6043 entries, 0 to 6042
Data columns (total 26 columns):
customerID                                 6043 non-null object
gender                                     6043 non-null int64
SeniorCitizen                              6043 non-null int64
Partner                                    6043 non-null int64
Dependents                                 6043 non-null int64
tenure                                     6043 non-null int64
PhoneService                               6043 non-null int64
MultipleLines                              6043 non-null int64
OnlineSecurity                             6043 non-null int64
OnlineBackup                               6043 non-null int64
DeviceProtection                           6043 non-null int64
TechSupport                                6043 non-null int64
StreamingTV                                6043 non-null int64
StreamingMovies                            6043 non-null int64
Contract  

In [ ]:
train_set.drop(train_set[['Attrition_No']].columns, axis = 1, inplace=True)

In [12]:
train_col_var = train_set.columns.values.tolist()
Y_list=['Churn']
X_list=[i for i in train_col_var if i not in Y_list]

In [25]:
X_list, Y_list
#X_list = X_list[1:]

(['gender',
  'SeniorCitizen',
  'Partner',
  'Dependents',
  'tenure',
  'PhoneService',
  'MultipleLines',
  'OnlineSecurity',
  'OnlineBackup',
  'DeviceProtection',
  'TechSupport',
  'StreamingTV',
  'StreamingMovies',
  'Contract',
  'PaperlessBilling',
  'MonthlyCharges',
  'TotalCharges',
  'InternetService_0',
  'InternetService_DSL',
  'InternetService_Fiber optic',
  'PaymentMethod_Bank transfer (automatic)',
  'PaymentMethod_Credit card (automatic)',
  'PaymentMethod_Electronic check',
  'PaymentMethod_Mailed check'],
 ['Churn'])

In [20]:
#特征选择
##如果变量不是很多，可以不一定进行
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear')
rfe = RFE(model,10)
rfe = rfe.fit(train_set[X_list],train_set[Y_list].values.ravel())
print(rfe.support_)
print(rfe.ranking_)

ValueError: could not convert string to float: 

In [32]:
#这个暂时不知道该怎么处理，还是手工处理的
select_colomns = ['gender',
  'SeniorCitizen',
  'Partner',
  'Dependents',
  'tenure',
  'PhoneService',
  'MultipleLines',
  'OnlineSecurity',
  'OnlineBackup',
  'DeviceProtection',
  'TechSupport',
  'StreamingTV',
  'StreamingMovies',
  'Contract',
  'PaperlessBilling',
  'InternetService_0',
  'InternetService_DSL',
  'InternetService_Fiber optic',
  'PaymentMethod_Bank transfer (automatic)',
  'PaymentMethod_Credit card (automatic)',
  'PaymentMethod_Electronic check',
  'PaymentMethod_Mailed check']
X_list=select_colomns
X_raw=train_set[X_list]
y=train_set[Y_list]
#X_raw=sample_train_set[X_list]
#y=sample_train_set[Y_list]

In [33]:
X_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6043 entries, 0 to 6042
Data columns (total 22 columns):
gender                                     6043 non-null int64
SeniorCitizen                              6043 non-null int64
Partner                                    6043 non-null int64
Dependents                                 6043 non-null int64
tenure                                     6043 non-null int64
PhoneService                               6043 non-null int64
MultipleLines                              6043 non-null int64
OnlineSecurity                             6043 non-null int64
OnlineBackup                               6043 non-null int64
DeviceProtection                           6043 non-null int64
TechSupport                                6043 non-null int64
StreamingTV                                6043 non-null int64
StreamingMovies                            6043 non-null int64
Contract                                   6043 non-null int64
PaperlessBi

In [34]:
#切割样本
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
X = preprocessing.minmax_scale(X_raw,feature_range=(-1,1))
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state = np.random)

In [ ]:
#增加抽样操作
#sample_train_set = train_set[train_set.Attrition_Yes==0].sample(n=300)
#sample_train_set = sample_train_set.append(train_set[train_set.Attrition_Yes==1])
sample_train_set.Attrition_Yes.value_counts()
sample_train_set.corrwith(sample_train_set.Attrition_Yes)
train_set.corrwith(train_set.Attrition_Yes)
train_set.cov()
#train_set.shape

In [35]:
#随机森林
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
#X = preprocessing.minmax_scale(x,feature_range=(-1,1))
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.3,random_state = np.random)
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train,Y_train.values.ravel())
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini', max_depth=None, max_features='auto', max_leaf_nodes=None, min_impurity_split=1e-07, min_samples_leaf=1, min_samples_split=2, min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1, oob_score=False, random_state=None, verbose=0, warm_start=False)
print('accuracy_score is :{}'.format(accuracy_score(Y_test,rf.predict(X_test))))
print('classification_report is :\n{}'.format(classification_report(Y_test,rf.predict(X_test))))
print('confusion_matrix is :\n{}'.format(confusion_matrix(Y_test,rf.predict(X_test))))

accuracy_score is :0.7760617760617761
classification_report is :
              precision    recall  f1-score   support

           0       0.82      0.88      0.85      1311
           1       0.62      0.49      0.55       502

    accuracy                           0.78      1813
   macro avg       0.72      0.69      0.70      1813
weighted avg       0.76      0.78      0.77      1813

confusion_matrix is :
[[1159  152]
 [ 254  248]]


In [36]:
## SVM
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
#数据归一化
#x = preprocessing.minmax_scale(x,feature_range=(-1,1))
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.3,random_state = np.random)
svc = SVC(gamma='auto')
svc.fit(X_train,Y_train.values.ravel())
print('accuracy_score is :{}'.format(accuracy_score(Y_test,svc.predict(X_test))))
print('classification_report is :\n{}'.format(classification_report(Y_test,svc.predict(X_test))))
print('confusion_matrix is :\n{}'.format(confusion_matrix(Y_test,svc.predict(X_test))))

accuracy_score is :0.8196359624931053
classification_report is :
              precision    recall  f1-score   support

           0       0.85      0.92      0.88      1358
           1       0.68      0.52      0.59       455

    accuracy                           0.82      1813
   macro avg       0.77      0.72      0.74      1813
weighted avg       0.81      0.82      0.81      1813

confusion_matrix is :
[[1248  110]
 [ 217  238]]


In [37]:
#线性回归
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.3,random_state = np.random)
logreg.fit(X_train,Y_train)
print('accuracy_score is :{}'.format(accuracy_score(Y_test,logreg.predict(X_test))))
print('classification_report is :\n{}'.format(classification_report(Y_test,logreg.predict(X_test))))
print('confusion_matrix is :\n{}'.format(confusion_matrix(Y_test,logreg.predict(X_test))))

accuracy_score is :0.7953667953667953
classification_report is :
              precision    recall  f1-score   support

           0       0.84      0.89      0.86      1329
           1       0.64      0.54      0.58       484

    accuracy                           0.80      1813
   macro avg       0.74      0.71      0.72      1813
weighted avg       0.79      0.80      0.79      1813

confusion_matrix is :
[[1181  148]
 [ 223  261]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [38]:
#朴素贝叶斯
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.3,random_state = np.random)
gnb.fit(X_train,Y_train)
print('accuracy_score is :{}'.format(accuracy_score(Y_test,gnb.predict(X_test))))
print('classification_report is :\n{}'.format(classification_report(Y_test,gnb.predict(X_test))))
print('confusion_matrix is :\n{}'.format(confusion_matrix(Y_test,gnb.predict(X_test))))

accuracy_score is :0.7214561500275786
classification_report is :
              precision    recall  f1-score   support

           0       0.90      0.70      0.79      1334
           1       0.48      0.77      0.60       479

    accuracy                           0.72      1813
   macro avg       0.69      0.74      0.69      1813
weighted avg       0.79      0.72      0.74      1813

confusion_matrix is :
[[937 397]
 [108 371]]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [47]:
#预测集处理
##预处理
cat_vars=['InternetService','PaymentMethod']
for var in cat_vars:
    cat_list = pd.get_dummies(predict_set[var],prefix = var)
    predict_set_with_dummy = predict_set.join(cat_list)
    predict_set = predict_set_with_dummy

In [48]:
predict_set.drop(predict_set[cat_vars].columns, axis = 1, inplace=True)

In [49]:
predict_X=predict_set[X_list]

In [51]:
predict_y = rf.predict(predict_X)
print(predict_y)
print(predict_y.reshape(-1,1))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [53]:
print(predict_y.reshape(-1,1))

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]


In [ ]:
predict_set.info()

In [ ]:
x_predict = df_predict[select_colomns]

In [ ]:
df1 = pd.get_dummies(df['Attrition'],prefix='Attrition')

In [ ]:
df1.corr(df1.Attrition_No)

In [ ]:
df1 = df1.drop(df1.columns[9],axis = 1)

In [ ]:
df.corrwith(df.Age)

In [ ]:
plt.annotate()